import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { api } from "../lib/api";
import type { PageResult, Patient } from "./types";
type Params = { search?: string; status?: string; page?: number; limit?: number };
const query = (params: Params) => new URLSearchParams(Object.entries(params).filter(([, value]) => value !== undefined && value !== "") as [string, string][]).toString(); const token = (state: any) => state.auth.accessToken as string | null;
export const fetchPatients = createAsyncThunk("patients/fetch", async (params: Params, { getState }) => api<PageResult<Patient>>(`/patients?${query(params)}`, { token: token(getState()) }));
export const savePatient = createAsyncThunk("patients/save", async ({ id, data }: { id?: string; data: Record<string, unknown> }, { getState }) => api<Patient>(id ? `/patients/${id}` : "/patients", { method: id ? "PATCH" : "POST", body: data, token: token(getState()) }));
export const removePatient = createAsyncThunk("patients/remove", async (id: string, { getState }) => { await api(`/patients/${id}`, { method: "DELETE", token: token(getState()) }); return id; });
const slice = createSlice({ name: "patients", initialState: { data: [] as Patient[], meta: { page: 1, limit: 10, totalPages: 1, totalResults: 0 }, loading: false, saving: false, error: null as string | null }, reducers: {}, extraReducers: (builder) => builder.addCase(fetchPatients.pending, (s) => { s.loading = true; s.error = null; }).addCase(fetchPatients.fulfilled, (s, a) => { s.loading = false; s.data = a.payload.results; s.meta = a.payload; }).addCase(fetchPatients.rejected, (s, a) => { s.loading = false; s.error = a.error.message || "Unable to load patients"; }).addCase(savePatient.pending, (s) => { s.saving = true; }).addCase(savePatient.fulfilled, (s) => { s.saving = false; }).addCase(savePatient.rejected, (s, a) => { s.saving = false; s.error = a.error.message || "Unable to save patient"; }).addCase(removePatient.fulfilled, (s, a) => { s.data = s.data.filter((p) => p.id !== a.payload); }) }); export default slice.reducer;
