"use client";
import { useEffect } from "react";
import { Activity, Stethoscope, UserRound, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAppDispatch, useAppSelector } from "@/app/store/hooks";
import { fetchDashboard } from "@/app/store/dashboardSlice";
const colors = ["#2b6eff", "#5b8cff", "#8bb0ff"];
export default function DashboardPage() { const dispatch = useAppDispatch(); const { data, loading, error } = useAppSelector((state) => state.dashboard); useEffect(() => { dispatch(fetchDashboard()); }, [dispatch]); if (loading || !data) return <div className="flex h-[70vh] flex-col items-center justify-center gap-3"><div className="h-12 w-12 animate-spin rounded-full border-4 border-[#2b6eff] border-t-transparent" />{error && <p className="text-sm text-red-600">{error}</p>}</div>; const stats = [{ title: "Total Doctors", value: data.totals.doctors, icon: Stethoscope }, { title: "Total Patients", value: data.totals.patients, icon: Users }, { title: "Avg Patients / Doctor", value: data.totals.doctors ? (data.totals.patients / data.totals.doctors).toFixed(1) : "0", icon: UserRound }, { title: "Critical Patients", value: data.patientsByStatus.find((item) => item._id === "critical")?.total || 0, icon: Activity }]; const conditions = data.patientsByStatus.map((item) => ({ name: item._id, value: item.total })); return <div className="space-y-8"><div><h1 className="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">Dashboard Overview</h1><p className="mt-1 text-sm text-gray-500">Live data from your Doctor Tracker API.</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div key={stat.title} className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-gray-500">{stat.title}</p><p className="mt-2 text-3xl font-bold text-gray-900">{stat.value}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#2b6eff] text-white"><stat.icon className="h-6 w-6" /></div></div></div>)}</div><div className="grid grid-cols-1 gap-6 lg:grid-cols-3"><ChartCard title="Patients per Doctor" className="lg:col-span-2"><BarChart data={data.patientsPerDoctor}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="doctorName" tick={{ fontSize: 11 }} /><YAxis /><Tooltip /><Bar dataKey="total" fill="#2b6eff" radius={[8, 8, 0, 0]} /></BarChart></ChartCard><ChartCard title="Patients by status"><PieChart><Pie data={conditions} dataKey="value" nameKey="name" innerRadius={55} outerRadius={85}>{conditions.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ChartCard></div><ChartCard title="Patient registrations over time"><LineChart data={data.patientsByDate}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis /><Tooltip /><Line type="monotone" dataKey="total" stroke="#2b6eff" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ChartCard></div>; }
function ChartCard({ title, children, className = "" }: { title: string; children: React.ReactElement; className?: string }) { return <div className={`rounded-2xl border border-gray-100 bg-white p-6 shadow-sm ${className}`}><h2 className="mb-6 text-lg font-semibold text-gray-900">{title}</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>; }
